base_url = 'https://jobinja.ir/jobs?&b=&filters%5Bjob_categories%5D%5B0%5D=&filters%5Bkeywords%5D%5B0%5D={}&filters%5Blocations%5D%5B0%5D={}&page={}'
adv_count_selector = '#js-jobSeekerSearchResult > div > div.col-md-9.col-xs-12 > section > div > div.o-listView__item.o-listView__itemWrap.c-jobSearchState.c-tagger.u-clearFix > div.c-jobSearchState__log.u-clearFix > h3 > span.c-jobSearchState__numberOfResultsEcho'
title_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > div.c-jobView__title.o-box__mainTitle.u-clearFix > div > h1'
salary_selcetor = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-jobView__firstInfoBox.c-infoBox > li:nth-child(5) > div'
job_experience_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-jobView__firstInfoBox.c-infoBox > li:nth-child(4) > div'
time_type_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-jobView__firstInfoBox.c-infoBox > li:nth-child(3) > div'
skill_requirement_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-infoBox.u-mB0 > li:nth-child(1) > div'
minimum_degree_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-infoBox.u-mB0 > li:nth-child(4) > div'
gender_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-infoBox.u-mB0 > li:nth-child(2) > div'
army_situation_selector = '#singleJob > div.c-forceToLogin__content > div > div.col-md-8.col-sm-12 > section > ul.c-infoBox.u-mB0 > li:nth-child(3) > div'
request_header = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'}
